import { ScanType } from "./types";

 export const projectMeta = [
  { title: "Org", subtitle: "Project X" },
  { title: "Owner", subtitle: "Nammagiri" },
  { title: "Total Scans", subtitle: "100" },
  { title: "Scheduled", subtitle: "1000" },
  { title: "Rescans", subtitle: "100" },
  { title: "Failed Scans", subtitle: "100" },
  { title: "Last Updated", subtitle: "10 mins ago" },
];

export const scanData: ScanType[] = [
  {
    id: "1",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 3,
    high: 2,
    medium: 1,
    low: 5,
    lastScan: "4d ago",
  },
  {
    id: "2",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 2,
    high: 1,
    medium: 2,
    low: 4,
    lastScan: "4d ago",
  },
  {
    id: "3",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 1,
    high: 3,
    medium: 0,
    low: 6,
    lastScan: "4d ago",
  },
  {
    id: "4",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 2,
    high: 2,
    medium: 1,
    low: 3,
    lastScan: "4d ago",
  },
  {
    id: "5",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 4,
    high: 1,
    medium: 2,
    low: 5,
    lastScan: "4d ago",
  },
  {
    id: "6",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 1,
    high: 2,
    medium: 3,
    low: 4,
    lastScan: "4d ago",
  },
  {
    id: "7",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    critical: 2,
    high: 1,
    medium: 1,
    low: 7,
    lastScan: "4d ago",
  },
  {
    id: "8",
    name: "Web App Servers",
    type: "Greybox",
    status: "Scheduled",
    progress: 100,
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    lastScan: "4d ago",
  },
  {
    id: "9",
    name: "Web App Servers",
    type: "Greybox",
    status: "Scheduled",
    progress: 100,
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    lastScan: "4d ago",
  },
  {
    id: "10",
    name: "IoT Devices",
    type: "Blackbox",
    status: "Failed",
    progress: 10,
    critical: 5,
    high: 3,
    medium: 2,
    low: 1,
    lastScan: "5d ago",
  },
  {
    id: "11",
    name: "Temp Data",
    type: "Blackbox",
    status: "Failed",
    progress: 10,
    critical: 2,
    high: 4,
    medium: 1,
    low: 0,
    lastScan: "5d ago",
  },
];
